inputs:
  ARTIFACT_FILENAME:
    required: true
  ARTIFACT_PATH:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v4
      with:
        compression-level: 9
        if-no-files-found: error
        name: ${{ inputs.ARTIFACT_FILENAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: 1
