inputs:
  USES_PATH:
    required: true
  USES_INPUTS:
    required: true
runs:
  using: composite
  steps:
    - uses: jenseng/dynamic-uses@v1
      with:
        uses: ${{ inputs.USES_PATH }}
        with: ${{ inputs.USES_INPUTS }}
